// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonaStatsApi.Data;

#nullable disable

namespace PersonaStatsApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260819205447_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("PersonaStatsApi.Models.SocialStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SocialStats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Level = 1,
                            Name = "Conocimiento",
                            Points = 0
                        },
                        new
                        {
                            Id = 2,
                            Level = 1,
                            Name = "Coraje",
                            Points = 0
                        },
                        new
                        {
                            Id = 3,
                            Level = 1,
                            Name = "Amabilidad",
                            Points = 0
                        },
                        new
                        {
                            Id = 4,
                            Level = 1,
                            Name = "Proeza",
                            Points = 0
                        },
                        new
                        {
                            Id = 5,
                            Level = 1,
                            Name = "Valentia",
                            Points = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
